@startuml

title __SKEWED ENGINE's Class Diagram__\n

  namespace com.apetrei.engine {
    abstract class com.apetrei.engine.Component {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.ConfigHandler {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.GameContainer {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.GameObject {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Input {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.ObjectManager {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Renderer {
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Window {
    }
  }
  

  namespace com.apetrei.engine {
    namespace components {
      class com.apetrei.engine.components.PlayerComponent {
      }
    }
  }
  

  namespace com.apetrei.engine {
    namespace components {
      class com.apetrei.engine.components.SpriteComponent {
      }
    }
  }
  

  namespace com.apetrei.engine {
    namespace components {
      class com.apetrei.engine.components.TransformComponent {
      }
    }
  }
  

  namespace com.apetrei.game {
    class com.apetrei.game.GameManager {
    }
  }
  

  com.apetrei.engine.Component o-- com.apetrei.engine.GameObject : parent
  com.apetrei.engine.GameContainer .up.|> java.lang.Runnable
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Input : input
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.ObjectManager : objectManager
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Renderer : renderer
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Window : window
  com.apetrei.engine.GameObject o-- com.apetrei.engine.GameContainer : gameContainer
  com.apetrei.engine.Input .up.|> java.awt.event.KeyListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseMotionListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseWheelListener
  com.apetrei.engine.Input o-- com.apetrei.engine.GameContainer : gameContainer
  com.apetrei.engine.Renderer o-- com.apetrei.engine.GameContainer : gc
  com.apetrei.engine.components.PlayerComponent -up-|> com.apetrei.engine.Component
  com.apetrei.engine.components.PlayerComponent o-- com.apetrei.engine.components.TransformComponent : transformComponent
  com.apetrei.engine.components.SpriteComponent -up-|> com.apetrei.engine.Component
  com.apetrei.engine.components.SpriteComponent o-- com.apetrei.engine.components.TransformComponent : transformComponent
  com.apetrei.engine.components.TransformComponent -up-|> com.apetrei.engine.Component


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
