@startuml

title __ENGINE's Class Diagram__\n

  namespace com.apetrei.engine {
    abstract class com.apetrei.engine.Component {
        + Component()
        {abstract} + componentRender()
        {abstract} + componentUpdate()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.ConfigHandler {
        {static} - UPDATE_CAP : double
        {static} - height : int
        {static} - scale : float
        {static} - title : String
        {static} - width : int
        {static} + getHeight()
        {static} + getScale()
        {static} + getTitle()
        {static} + getUpdateCap()
        {static} + getWidth()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.GameContainer {
        - running : boolean
        - thread : Thread
        + GameContainer()
        + getInput()
        + getObjectManager()
        + getRenderer()
        + getWindow()
        + run()
        + start()
        + stop()
        - dispose()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.GameObject {
        + active : boolean
        # components : ArrayList<Component>
        - uniqueTag : String
        + GameObject()
        + addComponent()
        + getComponent()
        + getGameContainer()
        + isActive()
        + render()
        + update()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Input {
        - NUM_KEYS : int
        - NUM_MOUSE_KEYS : int
        - keys : boolean[]
        - keysPast : boolean[]
        - mouseKeys : boolean[]
        - mouseKeysPast : boolean[]
        - mouseX : int
        - mouseY : int
        - scroll : int
        + Input()
        + getMouseX()
        + getMouseY()
        + getScroll()
        + isKeyDown()
        + isKeyPressed()
        + isKeyUp()
        + isMouseKeyDown()
        + isMouseKeyPressed()
        + isMouseKeyUp()
        + keyPressed()
        + keyReleased()
        + keyTyped()
        + mouseClicked()
        + mouseDragged()
        + mouseEntered()
        + mouseExited()
        + mouseMoved()
        + mousePressed()
        + mouseReleased()
        + mouseWheelMoved()
        + update()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.ObjectManager {
        # gameObjects : ArrayList<GameObject>
        + addGameObject()
        ~ ObjectManager()
        ~ renderObjects()
        ~ updateObjects()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Renderer {
        - graphics : Graphics
        - image : BufferedImage
        - pixels : int[]
        - pixelsH : int
        - pixelsW : int
        + RenderNow()
        + Renderer()
        + clear()
        + drawSprite()
        + setPixel()
    }
  }
  

  namespace com.apetrei.engine {
    class com.apetrei.engine.Window {
        - bufferStrategy : BufferStrategy
        - canvas : Canvas
        - frame : JFrame
        - graphics : Graphics
        + UpdateWindow()
        + Window()
        + getCanvas()
        + getFrame()
        + getGraphics()
    }
  }
  

  com.apetrei.engine.Component o-- com.apetrei.engine.GameObject : parent
  com.apetrei.engine.GameContainer .up.|> java.lang.Runnable
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Input : input
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.ObjectManager : objectManager
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Renderer : renderer
  com.apetrei.engine.GameContainer o-- com.apetrei.engine.Window : window
  com.apetrei.engine.GameObject o-- com.apetrei.engine.GameContainer : gameContainer
  com.apetrei.engine.Input .up.|> java.awt.event.KeyListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseMotionListener
  com.apetrei.engine.Input .up.|> java.awt.event.MouseWheelListener
  com.apetrei.engine.Input o-- com.apetrei.engine.GameContainer : gameContainer
  com.apetrei.engine.Renderer o-- com.apetrei.engine.GameContainer : gc


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
