package com.apetrei.engine.event;

public enum GlobalEvent {
    PLAYER_DESTROYED, OBJECTIVE_DESTROYED,OBJECTIVE_DAMAGED , ENEMY_DESTROYED,
    LEVEL1_COMPLETED,LEVEL2_COMPLETED,LEVEL3_COMPLETED,LEVEL4_COMPLETED,
    LEVEL1_WAVE1,LEVEL3_WAVE1,
    NULL
}
